### ISSUE TITLE
ERROR in Cannot read properties of undefined (reading 'pop')

### ISSUE THREAD

**Issue by decpk** [dvtng/react-loading-skeleton#169] opened 2023-03-06 12:26 UTC
**Describe the bug**
After Installing the latest version@3.2.0 then this error is showing on build

**To Reproduce**
Install the latest@3.2.0 and build it. It will throw this error.

**Versions**

- react-loading-skeleton version: 3.2.0
- Browser version: Version 112.0.5615.12 (Official Build) dev (arm64)

![image](https://user-images.githubusercontent.com/37063026/223109794-1465dd7c-8d24-4663-8c2b-d7489be568e2.png)

**Comment by decpk** [comment] 2023-03-06 12:27
Later, After downgraded to @3.1.1 then this issue get resolved.

**Comment by decpk** [comment] 2023-03-06 12:56
This issue only happening when importing `css` file.
**import 'bootstrap/dist/css/bootstrap.min.css';**

**Comment by srmagura** [comment] 2023-03-06 12:57
Hey @decpk, it seems most likely that this is an issue with your Webpack configuration. If you can share more details and/or submit a minimal reproducible example, I can look into it further.

**Comment by srmagura** [comment] 2023-03-18 00:21
Closing since this seems to be unrelated to react-loading-skeleton.

**Closed by srmagura** 2023-03-18 00:21 UTC
