### ISSUE TITLE
Emotion 9 and 10 are incompatible on the same screen

### ISSUE THREAD

**Issue by hoffination** [dvtng/react-loading-skeleton#33] opened 2019-09-18 10:57 UTC
Ran into a problem bumping my version of Storybook to 5 because of conflicting versions of Emotion. Here is a link detailing the problem: https://www.gitmemory.com/issue/emotion-js/emotion/1347/492623945

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at serializeStyles (main.3173126555acebfe0d1a.bundle.js:445)
    at css (vendors~main.ad7bd95803918bf0d539.bundle.js:643)
    at Module.keyframes (vendors~main.ad7bd95803918bf0d539.bundle.js:504)
    at Object../node_modules/@storybook/theming/dist/animation.js (vendors~main.ad7bd95803918bf0d539.bundle.js:7687)
    at __webpack_require__ (runtime~main.7b4918090cfe19b7778a.bundle.js:79)
    at Object../node_modules/@storybook/theming/dist/create.js (vendors~main.ad7bd95803918bf0d539.bundle.js:7845)
    at __webpack_require__ (runtime~main.7b4918090cfe19b7778a.bundle.js:79)
    at Object../node_modules/@storybook/theming/dist/index.js (vendors~main.ad7bd95803918bf0d539.bundle.js:8126)
    at __webpack_require__ (runtime~main.7b4918090cfe19b7778a.bundle.js:79)
    at Object../node_modules/@storybook/router/dist/visibility.js (vendors~main.ad7bd95803918bf0d539.bundle.js:7643)
```

**Comment by srmagura** [comment] 2021-09-29 00:52
Closing as duplicate of #80.

**Closed by srmagura** 2021-09-29 00:52 UTC
